### ISSUE TITLE
Subject parsing failed!!!!

### ISSUE THREAD

**Issue by shivanshu-semwal** [kevin1337x/Moodle_Bot#1]
# Subject parsing failed!!!

Here is the output of running the script-
```
					 SCRIPT BY Napster/taurus@KEVIN 

						 Moodle_Bot v1.0 




 #LOGGING IN 

 #LOGIN SUCCESSFUL 

 #SUBJECTS 
 ____________________________________________________________ 

 ____________________________________________________________ 


 #UPCOMING EVENTS 

Quiz 04 closesTomorrow, 9:55 AM
Assignment-1 is dueTomorrow, 10:00 PM
```

As you can see the subject parsing is not working. I commented out the some of your code.__(API request to googledoc.)__

**Comment by adityarawat1337x** [comment]
I'll see what I can do

**Comment by adityarawat1337x** [comment]
Is your internet working fine??... And if it is please make sure your
homepage is in card mode.ps check by inspecting that page if all the links
for subjects visible.

**Comment by adityarawat1337x** [comment]
or send me your username password on dm

**Comment by shivanshu-semwal** [comment]
Now it works. The problem was that I didn't had card mode on. 👍👍 Amazing work.👏👏👏
